services:
  web:
    build:
      context: ./frontend
      target: dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"